# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RippleRepositories' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RippleQueries
	pod 'RxSwift'
	pod 'RxCocoa'
	pod 'Alamofire'
	pod 'SwiftyJSON'
	pod 'SDWebImage'
	pod 'Toast-Swift'

  target 'RippleRepositoriesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RippleRepositoriesUITests' do
    # Pods for testing
  end

end
